# Generated by Django 5.0.1 on 2024-02-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_movies_username_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='username_added',
            field=models.CharField(max_length=250),
        ),
    ]
