# Generated by Django 5.0.1 on 2024-02-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_movies_username_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='img',
            new_name='image',
        ),
    ]
