# Generated by Django 5.0.1 on 2024-02-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_alter_movies_rls_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rls_date',
            field=models.DateField(),
        ),
    ]
